DX-471 - replace flake8 with ruff
carta/.github pull request #142
Opened 2023-04-26 22:38 UTC by saada

2023-04-26 23:50 UTC, aarontsharp approved these changes
🚀

2023-04-27 00:20 UTC, bensontrinh-carta approved these changes

2023-04-27 04:08 UTC, jimmylai requested changes
Ruff should be wrapped as an entry point like other linters to provide the consistent improved developer experience:
1. metrics tracking
2. show linter error in the context of code
3. autofixes
Without those we won't be able to understand developer experience when things go wrong or improve it over the long term.

2023-08-16 12:04 UTC, closed without merging

2023-08-16 12:04 UTC, saada commented
I give up